---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(tidyverse)
library(tidyseurat)
library(BayesPrism)
library(readxl)
library(janitor)
library(patchwork)
#library(biomaRt) gives problems with "select"
library(InstaPrism)
library(MuSiC)
library(TOAST)
library(SummarizedExperiment)
library(SingleCellExperiment)
library(tidySingleCellExperiment)
```

```{r}
dataset_name <- "hub_01"
path_raw_data_file <-  "..\\..\\raw_data\\cubi_cusco"


obj <- read_rds(paste0("intermediate_data/", dataset_name, "_integrated_", ".rds"))
combined_bulk<- read.csv(paste(path_raw_data_file,"hub_01_02_bulk\\counts_table_hub_01_02.csv", sep = "\\"))
hub_01_meta_data <-  read_csv( "intermediate_data/hub_01_meta_data.csv")

  

```




## select matching bulk samples according to sodar meta data
```{r}
hub_01_bulk_library_names <- hub_01_meta_data |> pull(sample)
hub_01_bulk_library_names <- hub_01_bulk_library_names |> str_replace_all("-",".")

combined_bulk <- combined_bulk |>  select(-gene,-X)
bk.dat <- combined_bulk[,hub_01_bulk_library_names] |> as.matrix() |>  t()
colnames(bk.dat) <- combined_bulk |> pull(ensembl_gene_id)
bk.dat[1:8,1:5]

```


## chose cell state labels, remove clusters
```{r}


cell.state.labels <- obj |> pull(harmony_clusters_res0.4) |> as.character()
table(cell.state.labels)


```


## make single cell mtx with ensemble ids from seurat object
```{r}
sc.dat_uncorrected <- obj@assays$uncorrected_RNA@layers$counts |> as.matrix() 

# Define your list of gene names
gene_names <- rownames(obj)

# Use the Ensembl database for humans (change the dataset for different species)
ensembl <- biomaRt::useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# Query Ensembl to get the Ensembl Gene IDs for your list of gene names
gene_mapping <- biomaRt::getBM(
  filters = "hgnc_symbol",    # Filter based on HGNC gene symbols
  attributes = c("hgnc_symbol", "ensembl_gene_id"),  # Retrieve HGNC symbols and Ensembl Gene IDs
  values = gene_names,        # The list of gene names to map
  mart = ensembl
)

# make named vactor for conversion
gene_vec <- gene_mapping$ensembl_gene_id
names(gene_vec)<- gene_mapping$hgnc_symbol
#sort gene names and ensmbl ids and by that the sc matx to allow conversion of mix of genenames and ensemble ids
ensgs <- gene_names[grepl("ENSG", gene_names)]
hpc<- gene_names[!grepl("ENSG", gene_names)]
colnames(sc.dat_uncorrected) <- colnames(obj)#cells
rownames(sc.dat_uncorrected) <- rownames(obj)#features
sc.dat_uncorrected <- sc.dat_uncorrected[c(ensgs,hpc),]#rearrange sc.dat_uncorrected

#convert gene names
hpc_to_ensgs <- gene_vec[hpc]
rownames(sc.dat_uncorrected) <- c(ensgs, hpc_to_ensgs)

sc.dat_uncorrected <- t(sc.dat_uncorrected)




sc.dat_background_corrected <- obj@assays$uncorrected_RNA@layers$counts |> as.matrix() 

# Define your list of gene names
gene_names <- rownames(obj)

# Use the Ensembl database for humans (change the dataset for different species)
ensembl <- biomaRt::useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# Query Ensembl to get the Ensembl Gene IDs for your list of gene names
gene_mapping <- biomaRt::getBM(
  filters = "hgnc_symbol",    # Filter based on HGNC gene symbols
  attributes = c("hgnc_symbol", "ensembl_gene_id"),  # Retrieve HGNC symbols and Ensembl Gene IDs
  values = gene_names,        # The list of gene names to map
  mart = ensembl
)

# make named vactor for conversion
gene_vec <- gene_mapping$ensembl_gene_id
names(gene_vec)<- gene_mapping$hgnc_symbol
#sort gene names and ensmbl ids and by that the sc matx to allow conversion of mix of genenames and ensemble ids
ensgs <- gene_names[grepl("ENSG", gene_names)]
hpc<- gene_names[!grepl("ENSG", gene_names)]
colnames(sc.dat_background_corrected) <- colnames(obj)#cells
rownames(sc.dat_background_corrected) <- rownames(obj)#features
sc.dat_background_corrected <- sc.dat_background_corrected[c(ensgs,hpc),]#rearrange sc.dat_background_corrected

#convert gene names
hpc_to_ensgs <- gene_vec[hpc]
rownames(sc.dat_background_corrected) <- c(ensgs, hpc_to_ensgs)

sc.dat_background_corrected <- t(sc.dat_background_corrected)

```



```{r}
DimPlot(obj, reduction = "umap.uncorrected_RNA", group.by = "cell_line_cellranger")
```



##########################
```{r}
sc.dat.filtered.pc.sig <- read_rds("intermediate_data/BayesPrsim_hub_01_sc.dat.filtered.pc.sig.rds")
bayesPrism_genes <- sc.dat.filtered.pc.sig |> colnames()
```

```{r}
sc.dat_corrected <- sc.dat_uncorrected[,bayesPrism_genes]
bk.dat_s <- bk.dat
bk.dat <- bk.dat[,colSums(bk.dat)>20]# doesnt change proportions
genes_keep_2 <- intersect(colnames(sc.dat_uncorrected),colnames(bk.dat))

bk.dat <- bk.dat[,genes_keep_2]
sc.dat_uncorrected <- sc.dat_uncorrected[,genes_keep_2]

```

```{r}
meta_data_arranged <- obj@meta.data[rownames(sc.dat_uncorrected),]
meta_data_arranged <- meta_data_arranged |> bind_cols(obj@reductions$umap.mnn@cell.embeddings[rownames(sc.dat_uncorrected),]) 

sce<- SingleCellExperiment(assays = list(counts = t(sc.dat_uncorrected)), colData=meta_data_arranged)



sce <- sce |> mutate(m_e_class =case_when(
  harmony_clusters_res0.1 == 1 ~ "M",
  harmony_clusters_res0.1 == 2 ~ "M",
  harmony_clusters_res0.1 == 3 ~ "M",
  harmony_clusters_res0.1 == 4 ~ "M",
  harmony_clusters_res0.1 == 0 ~ "E"
  
))
sce |> ggplot(aes(umapmnn_1, umapmnn_2, color=harmony_clusters_res0.4))+geom_point()+theme_void()
```
```{r}
sce <- sce |> filter(!harmony_clusters_res0.4%in%c("10"))

```


# music unfiltered


```{r}
sc_group_counts <- sce |> group_by(cell_line_cellranger, m_e_class) |> summarise(n=n())|> mutate(fraction=n/sum(n))

sc_m_e_bar_chart <-  sce |> group_by(cell_line_cellranger, m_e_class) |> summarise(n=n())|> mutate(fraction=n/sum(n)) |>
  ggplot(aes(cell_line_cellranger,fraction, fill = m_e_class)) +
  geom_col() +
  ggtitle("single cell proportions")

sc_cluster_chart <-  sce |> group_by(cell_line_cellranger, harmony_clusters_res0.4) |> summarise(n=n())|> mutate(fraction=n/sum(n)) |>
  ggplot(aes(cell_line_cellranger,fraction, fill = harmony_clusters_res0.4)) +
  geom_col() +
  ggtitle("single cell proportions")

sc_m_e_bar_chart/sc_cluster_chart
```

```{r}
Est.prop_filtered_10= music_prop(bulk.mtx = t(bk.dat),
                               sc.sce = sce,
                               clusters = 'm_e_class',
                               samples = 'cell_line_cellranger',
                               verbose = F)



p_m_e_filtered_10<- Est.prop_filtered_10$Est.prop.weighted |> as_tibble(rownames="sample") |> 
  left_join(hub_01_meta_data |> mutate(sample=str_replace_all(sample, "-", "."))) |> 
  pivot_longer(cols = M:E, names_to = "m_e_class" , values_to = "fraction") |>
    mutate(name=paste0("hIO_",cell_line)) |> 
  separate(name_2, into = "prep", remove = F) |> 
  mutate(prep_sample=paste0(sample, "_", prep)) |> 
   ggplot(aes(prep_sample,fraction, fill = m_e_class)) +  
  geom_col() +
  ggtitle("MuSiC")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
    facet_grid(~name,scales = "free_x", space = "free_x")

sc_m_e_bar_chart/p_m_e_filtered_10
ggsave("output/hub_01_MuSiC_sc_m_e_bar_chart_not10_REDUCED.png")

```

```{r}
Est.prop.2_filtered_10 = music_prop(bulk.mtx = t(bk.dat),
                               sc.sce = sce,
                               clusters = 'harmony_clusters_res0.4',
                               samples = 'cell_line_cellranger',
                               verbose = F)


p_clusters_filtered_10 <- Est.prop.2_filtered_10$Est.prop.allgene |>
  as_tibble(rownames="sample") |>
  left_join(hub_01_meta_data |> mutate(sample=str_replace_all(sample, "-", "."))) |> 
  mutate(name=paste0("hIO_",cell_line)) |> 
  pivot_longer(cols = "7":"8", names_to = "cluster" , values_to = "fraction") |>
    separate(name_2, into = "prep", remove = F) |> 
  mutate(prep_sample=paste0(sample, "_", prep)) |> 
   ggplot(aes(prep_sample,fraction, fill = cluster)) +  
  geom_col() +
  ggtitle("MuSiC")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
    facet_grid(~name,scales = "free_x", space = "free_x")

sc_cluster_chart/p_clusters_filtered_10
ggsave("output/hub_01_MuSiC_clusters_bar_chart_not10_REDUCED.png")
```

