---
title: "plots_for_harald"
format: html
editor: visual
---

```{r}
obj |> ggplot(aes(umapRNA_1,
             umapRNA_2,
             color=cell_line_cellranger))+
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  coord_fixed()

ggsave("output/2024-09-30_plots_for_harald/unintegrated_umap.png")

```

```{r}
obj |> ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=cell_line_cellranger))+
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  coord_fixed()

ggsave("output/2024-09-30_plots_for_harald/umap_mnn.png")

```
```{r}
obj |> ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=m_e_class))+
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  coord_fixed()

ggsave("output/2024-09-30_plots_for_harald/umap_mnn_harmony_m_e.png")

```
```{r}
obj |> ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=harmony_clusters_res0.4))+
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  coord_fixed()

ggsave("output/2024-09-30_plots_for_harald/umap_mnn_harmony_clusters_res0.4.png")

```

```{r}
obj |> ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=harmony_clusters_res0.1))+
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  coord_fixed()

ggsave("output/2024-09-30_plots_for_harald/umap_mnn_harmony_clusters_res0.1.png")

```

```{r}
obj |> 
  pivot_longer(cols=m.s.t_hio__basel_cell_like_1:m.s.t_hio__basel_cell_like_15) |>   group_by(name) |> 
  mutate(value=value/max(value)) |>
  ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=value)) +
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
    facet_wrap(~name, scales = "free")+
  scale_color_viridis_b()

ggsave("output/2024-09-30_plots_for_harald/umap_max_module_Scores.png")

```


```{r}
obj |> 
  pivot_longer(cols=m.s.t_hio__basel_cell_like_1:m.s.t_hio__basel_cell_like_15) |>   group_by(name) |> 
  mutate(value=value/max(value)) |>
  ggplot(aes(harmony_clusters_res0.1,
             value,
             fill=harmony_clusters_res0.1)) +
  geom_violin()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
    facet_wrap(~name, scales = "free")

ggsave("output/2024-09-30_plots_for_harald/umap_max_module_Scores.png")

```


```{r}
obj |> 
  pivot_longer(cols=m.s.t_hio__muc2_muc5ac_muc5b_goblet) |>  
 group_by(name) |> 
  mutate(value=value/max(value)) |>
  ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=value)) +
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  scale_color_viridis_b()+
  ggtitle("Module Score - Gobelet Cell-like")

ggsave("output/2024-09-30_plots_for_harald/umap_module Score - Gobelet Cell-like.png")

```

```{r}
obj |> 
  pivot_longer(cols=m.s.t_hio__enterocyte_progenitor) |>  
 group_by(name) |> 
  mutate(value=value/max(value)) |>
  ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=value)) +
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  scale_color_viridis_b()+
  ggtitle("Module Score - Enterocyte progenitor")

ggsave("output/2024-09-30_plots_for_harald/umap_Module Score - Enterocyte progenitor.png")

```


```{r}
obj |> 
  pivot_longer(cols=m.s.t_hio__basel_cell_like_10) |>  
 group_by(name) |> 
  mutate(value=value/max(value)) |>
  ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=value)) +
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  scale_color_viridis_b()+
  ggtitle("Module Score - Basal cell-like")

ggsave("output/2024-09-30_plots_for_harald/umap___basel_cell_like_10.png")

```

```{r}
obj |> 
  pivot_longer(cols=m.s.t_hio__basel_cell_like_2) |>  
 group_by(name) |> 
  mutate(value=value/max(value)) |>
  ggplot(aes(umapmnn_1,
             umapmnn_2,
             color=value)) +
  geom_point()+
  theme_void()+
  guides(colour = guide_legend(override.aes = list(size=5)))+
  scale_color_viridis_b()+
  ggtitle("Module Score - Basal cell-like 2")

ggsave("output/2024-09-30_plots_for_harald/umap___basel_cell_like_2.png")

```