---
title: "hub_0x_processing_after_qc"
format:
  html:
    embed-resources: true
    code-fold: true
editor: visual
params:
  dataset_name: "hub_01"
---

```{r message=FALSE}
library(tidyverse)
library(Seurat)
library(tidyseurat)
library(readxl)
library(janitor)
library(ggpubr)
library(BayesPrism)
library(ggpubr)
library(DT)
library(here)

#dataset_name <- "hub_01"
#dataset_name <- "hub_02"
dataset_name <- params$dataset_name # specified in the yaml header
recalculate_1 <- FALSE # seurat object processing combined object
recalculate_2 <- FALSE # seurat object processing sub object

seurat_obj <- read_rds(here("intermediate_data",paste0(dataset_name,"_filtered_seurat_obj.rds" ))
                       )
#paste0("intermediate_data\\",dataset_name,"_filtered_seurat_obj.rds") )
#subfilter_by <- "hIO_BIHi250-A"

```

```{r}
here()
print(dataset_name)
```

```{r message=FALSE}
if (recalculate_1) {
  # basic seurat processing for each assay
###--------------------------------------------------------------------------------------------
for (assay_it in Assays(seurat_obj)) {
  DefaultAssay(seurat_obj) <- assay_it
  seurat_obj <- seurat_obj |> 
    NormalizeData() 
  
  seurat_obj <- seurat_obj |>
    FindVariableFeatures(assay = assay_it) |> 
    ScaleData() 
  print("runPCA")
  seurat_obj <- seurat_obj |>
    RunPCA(assay = assay_it,reduction.name = paste0("pca.",assay_it)) 
  print("neighbors")
  seurat_obj <- seurat_obj |> FindNeighbors(dims = 1:30,
                                                  reduction = paste0("pca.",assay_it),
                                                  assay = assay_it) 
  
  print("clusters")
  seurat_obj <- seurat_obj |>  FindClusters(
    resolution = 0.8,
    verbose = FALSE,
    cluster.name =paste0(assay_it, "_clusters_leiden_res0.8"),algorithm=4
    #graph.name = paste0("kNN_","pca.",assay_it)
  ) 
  
  seurat_obj <- seurat_obj |>
    RunUMAP(dims = 1:30, reduction = paste0("pca.",assay_it),
            assay = assay_it,
            reduction.name =paste0("umap.",assay_it) )
  
  gc()
  


  }
###-----------------------------------------------------------------------------------
  write_rds(seurat_obj, file = here("intermediate_data", paste0(dataset_name,"_filtered_seurat_obj_processed.rds" )))
  
}
```
+
