---
title: "alt_test_yaml"
format: 
  dashboard:
    orientation: rows
    embed-resources: true
params: 
    param_plot_list_grob: "C:/Users/Danne/R_projects/hub_cubi_cusco/output/hub_10/plot_list_grob.rds"
    param_ggextra_plot_list_grob:
    "C:/Users/Danne/R_projects/hub_cubi_cusco/output/hub_10/plotified_plot_list_grob.rds"
    param_filter: 
---



```{r}

```



#  {.sidebar}

#### Cellbender called:

|          | *minimum counts per cell* |
|----------|---------------------------|
| **blba** | write something here      |

   

#### Prefiltering_2:

|           | *lower*              |
|-----------|----------------------|
| **dings** | write something here |
|           | write something here |



```{r setup}
#| warning: false
#| echo: false

library(tidyverse)
library(here)
library(grid)

#plot_list_grob <-  read_rds(here("output", "hub_10","plot_list_grob.rds"))
plot_list_grob <- read_rds(params$param_plot_list_grob)
#ggextra_plot_list_cellbender_cells <- read_rds(here("output", "hub_10","plot_list_grob.rds"))
#clean_plot_list_cellbender_cells <-  read_rds(here("output", "hub_10","clean_plot_list.rds"))
```


```{r }
#plotified_ggextra_plot_list_cellbender_cells <-   read_rds(here("output", "hub_10","plotified_plot_list_grob.rds"))
plotified_ggextra_plot_list_cellbender_cells <- read_rds(params$param_ggextra_plot_list_grob)

```


**Select for dotplot**

# Pre-Filtering

## Row {height="10%"}

### Column

lets just write some text here and see what happens

### Column

lets write some text here

## Row

### Column {.tabset}

```{r}
#| title: knee, marginal nCount_RNA - NA


grid::grid.newpage()
grid.draw(plotified_ggextra_plot_list_cellbender_cells$nCount_RNA_rank__vs__RNA_rank)

```

```{r}
#| title: knee, marginal nCount_RNA

grid::grid.newpage()
grid.draw(plotified_ggextra_plot_list_cellbender_cells[["nCount_RNA_rank__vs__RNA_rank_no_NA"]] )
```
```{r}
#| title: knee, marginal nCount_RNA

grid::grid.newpage()
grid.draw(plotified_ggextra_plot_list_cellbender_cells$nCount_RNA_rank__vs__RNA_rank_color_cellbender)
```
```{r}
#| title: cellbender, vireo, cellranger multi counts

grid::grid.newpage()
grid.draw(plot_list_grob$vireo_calls_barchart_grid_cellbender_vireo)

```

```{r}
#| title: cellbender, vireo, cellranger multi counts

grid::grid.newpage()
grid.draw(plot_list_grob$cellbender_prob__vs__RNA_rank_color_cellbender)

```

```{r}
#| title: histogram

grid::grid.newpage()
grid.draw(plot_list_grob$cellbender_prob_histogram)

```


```{r}
grid::grid.newpage()
grid.draw(plot_list_grob$dimplot_vireo)

```

```{r}
grid::grid.newpage()
grid.draw(plot_list_grob$dimplot_cellranger)

```
